name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: flags_user
      POSTGRES_PASSWORD: flags_test
      POSTGRES_DB: flags

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: flags_user
          POSTGRES_PASSWORD: flags_test
          POSTGRES_DB: flags
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.1"
          gleam-version: "1.12.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
